---
title: "GFW and Human Rights"
output: html_notebook
---
# Introduction
The project aims to address to research questions relating to human rights violations and fisheries:  

1. Can GFW be used to detect human rights violations in fisheries?
2. Do human rights violations, particularly forced labor, drive overfishing?

## Load libraries

```{r load_libraries}
library(lubridate)
library(tidyverse)
library(bigrquery)
library(plotly)
library(broom)
library(modelr)
```

## Load GFW data
```{r}
## Get all Thailand GFW Data
requery <- "no"
if (requery == "yes"){
sql <-  paste("SELECT
    year,
    mmsi, 
    timestamp, 
    lon, 
    lat, 
    hours, 
    measure_new_score, 
    distance_from_shore, 
    implied_speed, 
    eez_name
  FROM
    all_fishing_effort.all_fishing_effort_all_years
  WHERE
    flag_country_name = 'Thailand'",
  sep="")

project <-  "ucsb-gfw"
vesselQueryAll <- query_exec(sql,project,max_pages = Inf)

sql_vessels <-  paste("SELECT
  mmsi,
  country,
  general_vessel_type,
  length
FROM
  Vessel_Characteristics.complete_fishing_fleet_characteristics_2015",
sep="")
    
project <-  "ucsb-gfw"
vessel_characteristics <- query_exec(sql_vessels,project,max_pages = Inf)

save(vesselQueryAll,file="data/vesselQueryAll.Rdata")
save(vessel_characteristics,file="data/vessel_characteristics.Rdata")
} else {
  load("data/vesselQueryAll.Rdata")
  load("data/vessel_characteristics.Rdata")
}
```

```{r GFWdata}
thai_effort_processed <- vesselQueryAll %>%
  rename(Year = year) %>%
  mutate(Date = date(timestamp)) %>%
  mutate(Fishing = ifelse(measure_new_score >= 0.5 & 
                            !((distance_from_shore < 1000 & implied_speed < 1)),1,0)) %>%
  group_by(mmsi,Year) %>%
  summarize(total_hours_fished = sum(hours*Fishing),
            Annual_Active_Days = n_distinct(Date),
            Annual_Days_Fishing = n_distinct(Date[Fishing==1]),
            number_days_transit = n_distinct(Date[Fishing==0]),
            hours_per_day = total_hours_fished / Annual_Days_Fishing,
            number_fishing_pings = sum(Fishing),
            number_observation_pings = n(),
            ping_ratio = number_fishing_pings/number_observation_pings,
            day_ratio = Annual_Days_Fishing/Annual_Active_Days) %>%
  left_join(vessel_characteristics,by="mmsi") %>%
    arrange(-hours_per_day)

thai_effort_processed %>%
  plot_ly(x=~total_hours_fished,type="histogram",text=~mmsi) %>%
  layout(barmode = "overlay")

# knownOffenders <- thai_effort_processed %>%
#   filter(mmsi %in% c(567000445,567000421,567025800)) %>%
#   filter(Year == 2015) %>%
#   mutate(Offender = 1)
# 
# thai_effort_processed <- thai_effort_processed %>%
#   left_join(knownOffenders %>%
#               select(mmsi,
#                      Year,
#                      Offender),
#             by=c("mmsi","Year")) %>%
#   mutate(Offender = replace(Offender,is.na(Offender)==TRUE,0))
# 
# modelFit <- lm(total_hours_fished~Annual_Active_Days+0,thai_effort_processed,offset=rep(0, nrow(thai_effort_processed)))
# slope <- tidy(modelFit)$estimate
# thai_effort_processed %>%
#   plot_ly(x= ~Annual_Active_Days, y =~total_hours_fished,
#           mode="scatter") %>%
#   add_markers(size=~Annual_Days_Fishing,
#               color=~Annual_Days_Fishing,
#               text = ~paste('Vessel: ', mmsi,
#                             '<br>Year: ',Year,
#                             '<br>Annual Hours Fished: ',round(total_hours_fished),
#                             '<br>Annual Days Fished: ',round(Annual_Days_Fishing),
#                             '<br>Annual Days Active: ',round(Annual_Active_Days)),
#               name = "Individual Vessels") %>%
#   add_trace(x = c(0, max(thai_effort_processed$Annual_Active_Days)), 
#             y = c(0, slope*max(thai_effort_processed$Annual_Active_Days)),mode="lines",name="Linear Model Fit") %>%
#   layout(xaxis = list(title = "Annual Active Days"),yaxis = list(title = "Annual Hours Fished")) %>%
#   add_annotations(x = knownOffenders$Annual_Active_Days,
#                   y = knownOffenders$total_hours_fished,
#                   text = "Known suspect of<br>human trafficking",
#                   xref = "x",
#                   yref = "y",
#                   showarrow = TRUE,
#                   arrowhead = 4,
#                   arrowsize = .5,
#                   ax = c(-20,-0,-100),
#                   ay = c(-40,-60,-40))
```

```{r}
# HRModel <- glm(Offender ~ hours_per_day + Annual_Active_Days, data = thai_effort_processed, family = "binomial")
# offenderLikelihood <-predict(HRModel,list(hours_per_day = thai_effort_processed$hours_per_day,
#                                          Annual_Active_Days = thai_effort_processed$Annual_Active_Days),type="response") %>%
#   as.vector()
# 
# thai_effort_processed$Likelihood_of_Trafficking <- offenderLikelihood

newModel <- lm(total_hours_fished ~ Annual_Active_Days, data = thai_effort_processed)

thai_effort_processed <- thai_effort_processed %>%
  add_predictions(newModel) %>%
  add_residuals(newModel)

knownOffenders <- thai_effort_processed %>%
  filter(mmsi %in% c(567000445,567000421,567025800)) %>%
  filter(Year == 2015) %>%
  mutate(Offender = 1)

thai_effort_processed %>% 
  ggplot(aes(x=pred,y=total_hours_fished)) +
  geom_point() +
  geom_abline(yintercept = 0, slope = 1,color="red") +
  xlab("Predicted annual hours fished\n[hrs/year]") +
  ylab("Actual annual hours fished\n[hrs/year]")

thai_effort_processed %>%
  plot_ly(x= ~pred, y =~total_hours_fished,
          mode="scatter") %>%
  add_markers(color=~Annual_Active_Days,
              colors=c("black","red"),
              text = ~paste('Vessel: ', mmsi,
                            '<br>Year: ',Year,
                            '<br>Annual hours fished: ',round(total_hours_fished),
                            '<br>Annual days fished: ',round(Annual_Days_Fishing),
                            '<br>Annual days at sea: ',round(Annual_Active_Days),
                            '<br>Hours per day: ',round(hours_per_day,1),
                            '<br>Offender likelihood: ',round(offenderLikelihood,2)),
              name = "Individual Vessels") %>%
  layout(title = "Thai Fishing Vessels: 2012 - 2016",xaxis = list(title = "Predicted total annual fishing hours"),yaxis = list(title = "Actual total annual fishing hours")) %>%
  add_annotations(x = knownOffenders$pred,
                  y = knownOffenders$total_hours_fished,
                  text = "Known suspect of<br>human trafficking",
                  xref = "x",
                  yref = "y",
                  showarrow = TRUE,
                  arrowhead = 4,
                  arrowsize = .5,
                  ax = c(60,0,60),
                  ay = c(-40,-80,-40))  %>%
  add_trace(x = c(0, max(thai_effort_processed$pred)), 
            y = c(0, max(thai_effort_processed$pred)),mode="lines",name="45 degree line")

# thai_effort_processed %>%
#   plot_ly(x= ~Annual_Active_Days, y =~hours_per_day,
#           mode="scatter") %>%
#   add_markers(size=~Likelihood_of_Trafficking,
#               color=~Likelihood_of_Trafficking,
#               colors=c("black","red"),
#               text = ~paste('Vessel: ', mmsi,
#                             '<br>Year: ',Year,
#                             '<br>Annual hours fished: ',round(total_hours_fished),
#                             '<br>Annual days fished: ',round(Annual_Days_Fishing),
#                             '<br>Annual days at sea: ',round(Annual_Active_Days),
#                             '<br>Hours per day: ',round(hours_per_day,1),
#                             '<br>Offender likelihood: ',round(offenderLikelihood,2)),
#               name = "Individual Vessels") %>%
#   layout(title = "Thai Fishing Vessels: 2012 - 2016",xaxis = list(title = "Annual days at sea"),yaxis = list(title = "Hours fished per fishing day")) %>%
#   add_annotations(x = knownOffenders$Annual_Active_Days,
#                   y = knownOffenders$hours_per_day,
#                   text = "Known suspect of<br>human trafficking",
#                   xref = "x",
#                   yref = "y",
#                   showarrow = TRUE,
#                   arrowhead = 4,
#                   arrowsize = .5,
#                   ax = c(0,0,50),
#                   ay = c(-80,-80,-40))
```


```{r}
library(tmap)
library(rgdal)
library(sp)
library(leaflet)
eez <- readOGR(dsn = "data/World_EEZ_v9_20161021_LR", layer = "eez_lr", stringsAsFactors = FALSE)
eez@data$GeoName <- gsub(" Exclusive Economic Zone"," EEZ",eez@data$GeoName)
world <- readOGR(dsn = "data/TM_WORLD_BORDERS-0.3", layer = "TM_WORLD_BORDERS-0.3", stringsAsFactors = FALSE)
```


```{r}
vesselNumber <- 567000445
yearPlot <- 2015

fishingPoints <- vesselQueryAll %>%
  filter(mmsi == vesselNumber) %>%
  filter(measure_new_score >= 0.5) %>%
  filter(year == yearPlot) %>%
  filter(!(distance_from_shore < 1000 & implied_speed < 1)) %>%
  select(lon,
         lat) %>%
  SpatialPoints()

transitPoints <- vesselQueryAll %>%
  filter(mmsi == vesselNumber) %>%
  filter(measure_new_score < 0.5 & !(distance_from_shore < 1000 & implied_speed < 1)) %>%
  filter(year == yearPlot) %>%
  select(lon,
         lat) %>%
  SpatialPoints()

portPoints <- vesselQueryAll %>%
  filter(mmsi == vesselNumber) %>%
  filter(year == yearPlot & (distance_from_shore < 1000 & implied_speed < 1)) %>%
  select(lon,
         lat) %>%
  SpatialPoints()

eezOverlap <- overlay<-raster::intersect(eez,
                                         rbind(fishingPoints,
                              transitPoints,
                              portPoints))

extentPoints <- rbind(fishingPoints,
                              transitPoints,
                              portPoints) %>%
  bbox()


# qtm(world,
#          bbox = extentPoints, title=paste("Vessel: ",vesselNumber,"\nYear: ",yearPlot),style="cobalt") +
#   tm_borders() +
#    tm_shape(fishingPoints) +
#   tm_dots(col="red") +
#   tm_shape(transitPoints) +
#   tm_dots(col="blue") +
#   tm_shape(portPoints) +
#   tm_dots(col="green") +
#   tm_shape(eezOverlap) +
#   tm_borders(col="orange") +
#   tm_text("GeoName",size=1) +
#   tm_add_legend(type="symbol",labels=c("Transit","Fishing","Port"),col=c("blue","red","green"),shape=16,size=0.25)

leaflet() %>%
  # fitBounds(0, 60, 35, 72) %>%
  addTiles(group = "OSM (default)") %>%
  addPolygons(data = eez,
    fillOpacity = 0.15, 
    fillColor = "blue", 
    stroke=TRUE,
    weight=1,
    color="black",
    popup = ~paste0("<font color=#000000>",
      "<b>EEZ: </b>", GeoName, "<br>",
    "</font>"))  %>%
  addCircleMarkers(data=transitPoints,
              color="blue",
              stroke=FALSE,
              fillOpacity = 0.5,
              radius = 3,
              group = "Transit (Blue)")  %>%
  addCircleMarkers(data=fishingPoints,
              color="red",
              stroke=FALSE,
              fillOpacity = 0.5,
              radius = 3,
              group = "Fishing (Red)")  %>%
  addCircleMarkers(data=portPoints,
              color="green",
              stroke=FALSE,
              fillOpacity = 0.5,
              radius = 3,
              group = "Port (Green)") %>%
  fitBounds(lng1=extentPoints[1],lat1=extentPoints[2],lng2=extentPoints[3],lat2=extentPoints[4]) %>%
  addLayersControl(
    overlayGroups = c("Fishing (Red)", "Transit (Blue)","Port (Green)"),
    options = layersControlOptions(collapsed = FALSE)
  )
```

```{r, eval=FALSE}
## Get global GFW Data
requery <- "no"
if (requery == "yes"){
  
  sql <- "
  SELECT
    YEAR(timestamp) year,
    mmsi, 
    flag_country_name,
    CASE 
      WHEN measure_new_score >=.5 AND NOT (distance_from_shore < 1000 AND implied_speed < 1) THEN 1
      WHEN measure_new_score >=0 THEN 0
    END fishing,
    SUM(hours) hours,
    COUNT(DISTINCT DATE(timestamp)) days,
    COUNT(DISTINCT timestamp) pings
  FROM 
    [world-fishing-827:gfw_research.FAO]
  WHERE
    _PARTITIONTIME BETWEEN timestamp('2012-01-01')
    AND timestamp('2016-12-31')
  GROUP BY
    mmsi,
    year, 
    flag_country_name,
    fishing"
  
  project <-  "ucsb-gfw"

  vesselQueryGlobal <- query_exec(sql,project,max_pages = Inf)
  
save(vesselQueryGlobal,file="data/vesselQueryGlobal.Rdata")
} else {
  load("data/vesselQueryGlobal.Rdata")
}

## Get global GFW Data for vessel info
requery <- "no"
if (requery == "yes"){
  
  sql <- "
  SELECT
    mmsi,
    average_length,
    avg_width,
    inferred_label_allyears,
    fraction_time_high_seas
  FROM 
    [world-fishing-827:gfw_research.vessel_info_20170405]
  GROUP BY
    mmsi,
    average_length,
    avg_width,
    inferred_label_allyears,
    fraction_time_high_seas"
  
  project <-  "ucsb-gfw"

  vesselInfo <- query_exec(sql,project,max_pages = Inf)
  
save(vesselInfo,file="data/vesselInfo.Rdata")
} else {
  load("data/vesselInfo.Rdata")
}

vesselQueryGlobalProcessed <- vesselQueryGlobal %>%
  gather(key,val,hours:pings) %>%
  unite(key2,fishing,key) %>%
  spread(key2,val,fill=0) %>%
  rename(total_hours_fished = `1_hours`,
         Annual_Days_Fishing = `1_days`,
         Annual_Active_Days  = `0_days`,
         number_fishing_pings = `1_pings`,
         number_observation_pings = `0_pings`) %>%
  mutate(hours_per_day = total_hours_fished / Annual_Days_Fishing,
         ping_ratio = number_fishing_pings/number_observation_pings,
         day_ratio = Annual_Days_Fishing/Annual_Active_Days) %>%
  select(-`0_hours`)  %>%
  left_join(vesselInfo,by="mmsi") %>%
  filter(Annual_Days_Fishing > 0 & 
           !is.na(average_length) &
           !is.na(avg_width) &
           !is.na(inferred_label_allyears) &
           !is.na(fraction_time_high_seas))

globalModel <- lm(total_hours_fished ~ 
                    Annual_Active_Days + 
                    average_length +
                    avg_width +
                    factor(inferred_label_allyears) +
                    fraction_time_high_seas +
                    factor(flag_country_name) + 
                    0 + 
                    offset(rep(0, nrow(vesselQueryGlobalProcessed))), data =vesselQueryGlobalProcessed)

vesselQueryGlobalProcessed <- vesselQueryGlobalProcessed %>%
                    add_predictions(globalModel) %>%
                    add_residuals(globalModel)
                  
vesselQueryGlobalProcessed %>% 
  mutate(Thailand = ifelse(flag_country_name == "Thailand","Thailand","Not Thailand")) %>%
  ggplot(aes(x=pred,y=total_hours_fished)) +
  geom_point(aes(color=Thailand)) +
  geom_abline(intercept = 0, slope = 1,color="red") +
  xlab("Predicted annual hours fished\n[hrs/year]") +
  ylab("Actual annual hours fished\n[hrs/year]")
```

