---
title: "Detecting forced labor in fisheries - Econ model Proof of Concept"
author: Sustainable Fisheries Group, UCSB
output: html_notebook
---

# Setup
```{r}
library(tidyverse)
library(bigrquery)
project <-  "ucsb-gfw"
```

# Create relevant vessel table

Let's first look at US trawlers. We do not expect to see any forced labor in this fleet.

```{r}
# First, get all relevant vessel info

flag_poc <- "USA"
gear_poc <- "trawlers"

sql<-glue::glue("
#standardSQL
WITH
master AS(SELECT
mmsi,
year,
best_flag,
best_label,
best_tonnage,
best_length,
best_engine_power
FROM `world-fishing-827.gfw_research.vessel_info_20180518`
WHERE
best_flag = '{flag_poc}'
AND best_label = '{gear_poc}'
AND is_active
AND on_fishing_list_nn")

# Run new query. Delete old table, upload new one
bq_table(project = project,table = "poc_vessel_info",dataset = "human_rights") %>% 
  bq_table_delete()
bq_project_query(project,sql, destination_table = bq_table(project = project,table = "poc_vessel_info",dataset = "human_rights"),use_legacy_sql = FALSE, allowLargeResults = TRUE)
```


# Create table of all fishing voyages between 2012-2017 for that fleet

```{r}
sql <-"
#standardSQL
WITH
master AS(SELECT
anchorages.mmsi mmsi,
anchorages.from_anchorage_id from_anchorage_id,
CONCAT(b.anchor_group,
'-',
b.label) from_anchorage_name,
b.label from_port_name,
anchorages.departure_timestamp departure_timestamp,
anchorages.to_anchorage_id to_anchorage_id,
CONCAT(c.anchor_group,
'-',
c.label) to_anchorage_name,
c.label to_port_name,
anchorages.arrival_timestamp arrival_timestamp,
anchorages.flag flag,
anchorages.gear gear,
anchorages.tonnage tonnage,
anchorages.length length,
anchorages.engine_power engine_power
FROM (
SELECT
anchor1.mmsi mmsi,
anchor2.best_flag flag,
anchor2.best_label gear,
anchor2.best_tonnage tonnage,
anchor2.best_length length,
anchor2.best_engine_power engine_power,
anchor2.anchorage_id from_anchorage_id,
anchor2.event_end departure_timestamp,
anchor1.anchorage_id to_anchorage_id,
anchor1.event_start arrival_timestamp
FROM (
SELECT
vessel_1_id mmsi,
event_start,
event_end,
anchorage_id,
ROW_NUMBER() OVER (PARTITION BY vessel_1_id ORDER BY event_start) rn
FROM
`world-fishing-827.gfw_research.voyage_events_all_vessels_20180307`
WHERE
event_type = 'anchorage'
AND vessel_1_id IN (
SELECT
mmsi
FROM
`human_rights.poc_vessel_info`)) anchor1
JOIN (
SELECT
*,
rn+1 rn_plus
FROM ( (
SELECT
vessel_1_id mmsi,
EXTRACT(YEAR FROM event_start) AS year,
event_start,
event_end,
anchorage_id,
ROW_NUMBER() OVER (PARTITION BY vessel_1_id ORDER BY event_start) rn
FROM
`world-fishing-827.gfw_research.voyage_events_all_vessels_20180307`
WHERE
event_type = 'anchorage') voy_info
LEFT JOIN (
SELECT
mmsi mmsi_info,
year year_info,
best_flag,
best_label,
best_tonnage,
best_length,
best_engine_power
FROM
`human_rights.poc_vessel_info`) ves_info
ON
voy_info.mmsi = ves_info.mmsi_info
AND voy_info.year = ves_info.year_info)) anchor2
ON
anchor1.mmsi = anchor2.mmsi
AND anchor1.rn = anchor2.rn_plus) anchorages
LEFT JOIN (
SELECT
s2id,
label,
anchor_group
FROM
`world-fishing-827.gfw_research.named_anchorages_20171120`) b
ON
anchorages.from_anchorage_id = b.s2id
LEFT JOIN (
SELECT
s2id,
label,
anchor_group
FROM
`world-fishing-827.gfw_research.named_anchorages_20171120`) c
ON
anchorages.to_anchorage_id = c.s2id
)

SELECT
*
FROM
master
WHERE
NOT gear IS NULL
"

bq_table(project = project,table = "poc_voyages_with_anchorages",dataset = "human_rights") %>% 
  bq_table_delete()

bq_project_query(project,sql, destination_table = bq_table(project = project,table = "poc_voyages_with_anchorages",dataset = "human_rights"),
                 use_legacy_sql = FALSE, allowLargeResults = TRUE)
```

# Extract all rendezvous events during those voyages
```{r}
sql<-"
#standardSQL
  WITH transshipment_ids AS(
  SELECT
    transshipment_vessel_id trans_mmsi,
    TRUE transhipment_vessel
  FROM
    `world-fishing-827.gfw_research.encounters_fishing_transshipment_20180327`),
  bunker_ids AS(
  SELECT
    mmsi bunker_mmsi,
    TRUE bunker_vessel
  FROM
    `world-fishing-827.gfw_research.bunker_vessels_11072017` ),
  fishing_ids AS(
  SELECT
    mmsi fishing_mmsi,
    TRUE fishing_vessel
  FROM
    `world-fishing-827.gfw_research.vessel_info_20180518`
  WHERE
    on_fishing_list_nn ),
  rendezvous_table AS(
  SELECT
    vessel_1_id,
    vessel_2_id,
    event_start,
    event_end
  FROM
    `world-fishing-827.gfw_research.voyage_events_all_vessels_20180307`
  WHERE
    event_type = 'rendezvous'),
  voyages AS(
  SELECT
    mmsi,
    departure_timestamp,
    from_anchorage_id,
    arrival_timestamp,
    to_anchorage_id
  FROM
    `human_rights.poc_voyages_with_anchorages`),
  table_with_vessels AS(
  SELECT
    *
  FROM
    rendezvous_table
  JOIN
    transshipment_ids
  ON
    (rendezvous_table.vessel_1_id = transshipment_ids.trans_mmsi
      OR rendezvous_table.vessel_2_id = transshipment_ids.trans_mmsi)
  JOIN
    bunker_ids
  ON
    (rendezvous_table.vessel_1_id = bunker_ids.bunker_mmsi
      OR rendezvous_table.vessel_2_id = bunker_ids.bunker_mmsi)
  JOIN
    fishing_ids
  ON
    (rendezvous_table.vessel_1_id = fishing_ids.fishing_mmsi
      OR rendezvous_table.vessel_2_id = fishing_ids.fishing_mmsi) ),
  joined_table AS(
  SELECT
    *,
    (transhipment_vessel
      AND fishing_vessel) encounter_transshipment,
    (bunker_vessel
      AND fishing_vessel) encounter_bunker,
    (fishing_vessel
      AND fishing_vessel) encounter_fishing,
    (NOT ((transhipment_vessel
          AND fishing_vessel)
        OR (bunker_vessel
          AND fishing_vessel)
        OR (fishing_vessel
          AND fishing_vessel))) encounter_unspecified
  FROM
    table_with_vessels
  JOIN
    voyages
  ON
    (table_with_vessels.vessel_1_id = voyages.mmsi
      OR table_with_vessels.vessel_2_id = voyages.mmsi)
    AND table_with_vessels.event_start >voyages.departure_timestamp
    AND table_with_vessels.event_end < voyages.arrival_timestamp)
SELECT
  mmsi,
  departure_timestamp,
  from_anchorage_id,
  arrival_timestamp,
  to_anchorage_id,
  (SUM(CASE WHEN encounter_transshipment THEN 1 ELSE 0 END)) encounters_transshipment,
  (SUM(CASE WHEN encounter_bunker THEN 1 ELSE 0 END)) encounters_bunker,
  (SUM(CASE WHEN encounter_fishing THEN 1 ELSE 0 END)) encounters_fishing,
  (SUM(CASE WHEN encounter_unspecified THEN 1 ELSE 0 END)) encounters_unspecified
FROM
  joined_table
GROUP BY
  mmsi,
  departure_timestamp,
  from_anchorage_id,
  arrival_timestamp,
  to_anchorage_id"

bq_table(project = project,table = "poc_rendezvouses",dataset = "human_rights") %>% 
  bq_table_delete()

bq_project_query(project,sql, destination_table = bq_table(project = project,table = "poc_rendezvouses",dataset = "human_rights"),
                 use_legacy_sql = FALSE, allowLargeResults = TRUE)
```


# Extract AIS info from those voyages
# THIS WORKED
```{r}
#standardSQL
sql<-"WITH rendezvous_table AS(
  SELECT
    vessel_1_id,
    vessel_2_id,
    event_start,
    event_end
  FROM
    `world-fishing-827.gfw_research.voyage_events_all_vessels_20180307`
  WHERE
    event_type = 'rendezvous'),
  voyages AS(
  SELECT
    mmsi,
    departure_timestamp,
    from_anchorage_id,
    arrival_timestamp,
    to_anchorage_id
  FROM
    `human_rights.poc_voyages_with_anchorages`),
  joined_table AS(
  SELECT
    *
  FROM
    rendezvous_table
  JOIN
    voyages
  ON
    (rendezvous_table.vessel_1_id = voyages.mmsi
      OR rendezvous_table.vessel_2_id = voyages.mmsi)
    AND rendezvous_table.event_start >voyages.departure_timestamp
    AND rendezvous_table.event_end < voyages.arrival_timestamp)
SELECT
  mmsi,
  departure_timestamp,
  from_anchorage_id,
  arrival_timestamp,
  to_anchorage_id,
  COUNT(*) number_rendezvouses
FROM
  joined_table
GROUP BY
  mmsi,
  departure_timestamp,
  from_anchorage_id,
  arrival_timestamp,
  to_anchorage_id""
```

# THIS DIDN'T
```{r}
# Get NTZ area of each EEZ
# Data from https://www.protectedplanet.net/marine
# Only interested in no-take area. Not interested in Anarctica
ntzs <- read.csv("../data/WDPA_Mar2018_marine-csv/WDPA_Mar2018_marine-csv.csv",stringsAsFactors = FALSE) %>%
  filter(NO_TAKE == "All") %>%
  .$WDPAID %>%
  unique()

ntz_filter <- paste(paste0("regions LIKE '%mpant:",ntzs,"%'"),collapse=" OR ")

sql<-glue::glue("
#standardSQL
  WITH ping_info AS (
  SELECT
    mmsi,
    lat start_lat,
    lon start_lon,
    timestamp start_timestamp,
    next_lat end_lat,
    next_lon end_lon,
    next_timestamp end_timestamp,
    hours,
    avg_distance_km,
    eez_iso3,
    (CASE
        WHEN nnet_score = 1 AND NOT (distance_from_shore < 1000 AND implied_speed < 1) THEN hours
        ELSE 0 END) nnet_hours,
    (CASE
        WHEN {ntz_filter} THEN TRUE
        ELSE FALSE END) in_ntz
  FROM
    `world-fishing-827.gfw_research.nn`
  WHERE
    lat < 90
    AND lat > -90
    AND lon < 180
    AND lon >-180
    AND _PARTITIONTIME BETWEEN TIMESTAMP('2012-01-01')
    AND TIMESTAMP('2017-12-31')
    AND mmsi IN (
    SELECT
      mmsi
    FROM
      `human_rights.poc_voyages_with_anchorages`)),
  voyage_info AS(
  SELECT
    mmsi,
    flag,
    from_anchorage_id,
    from_anchorage_name,
    from_port_name,
    departure_timestamp,
    to_anchorage_id,
    to_anchorage_name,
    to_port_name,
    arrival_timestamp,
    gear,
    engine_power
  FROM
    `ucsb-gfw.human_rights.poc_voyages_with_anchorages`),
  ais_info AS(
  SELECT
    ping_info.mmsi mmsi,
    voyage_info.flag flag,
    voyage_info.gear gear,
    voyage_info.engine_power engine_power,
    DATE_TRUNC(DATE(ping_info.start_timestamp), MONTH) month,
    DATE_TRUNC(DATE(ping_info.start_timestamp), DAY) day,
    ping_info.start_lat start_lat,
    ping_info.start_lon start_lon,
    ping_info.start_timestamp,
    ping_info.hours hours,
    ping_info.nnet_hours nnet_hours,
    ping_info.avg_distance_km avg_distance_km,
    voyage_info.from_anchorage_id from_anchorage_id,
    voyage_info.from_anchorage_name from_anchorage_name,
    voyage_info.from_port_name from_port_name,
    voyage_info.departure_timestamp departure_timestamp,
    voyage_info.to_anchorage_id to_anchorage_id,
    voyage_info.to_anchorage_name to_anchorage_name,
    voyage_info.to_port_name to_port_name,
    voyage_info.arrival_timestamp arrival_timestamp,
    (NOT ping_info.eez_iso3 IS NULL AND NOT ping_info.eez_iso3 = voyage_info.flag AND ping_info.nnet_hours > 0) fishing_foreign_eez,
    (ping_info.eez_iso3 IS NULL AND ping_info.nnet_hours > 0) fishing_high_seas,
    (ping_info.in_ntz AND ping_info.nnet_hours > 0) fishing_ntz
  FROM
    ping_info
  LEFT JOIN
    voyage_info
  ON
    ping_info.mmsi = voyage_info.mmsi
    AND ping_info.start_timestamp > voyage_info.departure_timestamp
    AND ping_info.start_timestamp < voyage_info.arrival_timestamp)
SELECT
  *
FROM
  ais_info
"
)

bq_table(project = project,table = "poc_voyage_ais_positions",dataset = "human_rights") %>% 
  bq_table_delete()
bq_project_query(project,query = sql, destination_table =  bq_table(project = project,table = "poc_voyage_ais_positions",dataset = "human_rights"),
                 use_legacy_sql = FALSE, allowLargeResults = TRUE)
```

# Grid AIS positions
```{r}
grid_size <- 0.5 # Grid in degrees
suspicious_cutff <- 4 # How many standard deviations from mean does revenue/cost ratio need to be to be suspicious?
sql <-glue::glue("
#standardSQL
  WITH grid_base AS(
  SELECT
    mmsi,
    gear,
    flag,
    month,
    engine_power,
    FLOOR(start_lat/{grid_size}) * {grid_size} lat_bin,
    FLOOR(start_lon/{grid_size}) * {grid_size} lon_bin,
    from_anchorage_id,
    from_anchorage_name,
    from_port_name,
    departure_timestamp,
    DATE(departure_timestamp) departure_date,
    to_anchorage_id,
    to_anchorage_name,
    to_port_name,
    arrival_timestamp,
    SUM(hours) hours,
    SUM(nnet_hours) fishing_hours,
    SUM(hours - nnet_hours) * engine_power travel_effort_kWH,
    SUM(nnet_hours) * engine_power fishing_effort_kWH,
    SUM(avg_distance_km) distance_km,
    (SUM(CASE WHEN fishing_foreign_eez THEN 1 ELSE 0 END) > 0) fishing_foreign_eez,
    (SUM(CASE WHEN fishing_high_seas THEN 1 ELSE 0 END) > 0) fishing_high_seas,
    (SUM(CASE WHEN fishing_ntz THEN 1 ELSE 0 END) > 0) fishing_ntz
  FROM
    `human_rights.poc_voyage_ais_positions`
  WHERE
    NOT flag IS NULL
  GROUP BY
    mmsi,
    gear,
    flag,
    month,
    engine_power,
    lat_bin,
    lon_bin,
    from_anchorage_id,
    from_anchorage_name,
    from_port_name,
    departure_timestamp,
    departure_date,
    to_anchorage_id,
    to_anchorage_name,
    to_port_name,
    arrival_timestamp),
  voyage_info AS(
  SELECT
    mmsi voy_mmsi,
    gear voy_gear,
    flag voy_flag,
    month voy_month,
    from_anchorage_id voy_from_anchorage_id,
    departure_timestamp voy_departure_timestamp,
    SUM(hours - nnet_hours) * engine_power voyage_travel_effort_kWH,
    SUM(nnet_hours) * engine_power voyage_fishing_effort_kWH
  FROM
    `human_rights.poc_voyage_ais_positions`
  GROUP BY
    mmsi,
    gear,
    flag,
    month,
    engine_power,
    from_anchorage_id,
    departure_timestamp),
  voyage_grids AS(
  SELECT
    *
  FROM
    grid_base
  LEFT JOIN
    voyage_info
  ON
    grid_base.mmsi = voyage_info.voy_mmsi
    AND grid_base.gear = voyage_info.voy_gear
    AND grid_base.flag = voyage_info.voy_flag
    AND grid_base.month = voyage_info.voy_month
    AND grid_base.from_anchorage_id = voyage_info.voy_from_anchorage_id
    AND grid_base.departure_timestamp = voyage_info.voy_departure_timestamp),
  voyage_grids_2 AS(
  SELECT
    *
    EXCEPT(voy_mmsi, voy_gear, voy_flag, voy_month, voy_from_anchorage_id,voy_departure_timestamp),
    (CASE WHEN fishing_effort_kWH >0 THEN fishing_effort_kWH / (voyage_travel_effort_kWH * fishing_effort_kWH / voyage_fishing_effort_kWH + fishing_effort_kWH)
      ELSE NULL
      END) revenue_cost_ratio
  FROM
    voyage_grids),
  summary_grids AS(
  SELECT
    flag sum_flag,
    gear sum_gear,
    month sum_month,
    lat_bin sum_lat_bin,
    lon_bin sum_lon_bin,
    AVG(revenue_cost_ratio) mean_revenue_cost_ratio,
    STDDEV(revenue_cost_ratio) sd_revenue_cost_ratio
  FROM
    voyage_grids_2
  GROUP BY
    sum_flag,
    sum_gear,
    sum_month,
    sum_lat_bin,
    sum_lon_bin)
SELECT
  *,
  (revenue_cost_ratio < mean_revenue_cost_ratio - {suspicious_cutff} * sd_revenue_cost_ratio) suspicious_econ
FROM
  voyage_grids_2
LEFT JOIN
  summary_grids
ON
  voyage_grids_2.flag = summary_grids.sum_flag
  AND voyage_grids_2.gear = summary_grids.sum_gear
  AND voyage_grids_2.month = summary_grids.sum_month
  AND voyage_grids_2.lat_bin = summary_grids.sum_lat_bin
  AND voyage_grids_2.lon_bin = summary_grids.sum_lon_bin
  ")
bq_table(project = project,table = "poc_voyages_gridded",dataset = "human_rights") %>% 
  bq_table_delete()
bq_project_query(project,query = sql, destination_table = bq_table(project = project,table = "poc_voyages_gridded",dataset = "human_rights"),
                 allowLargeResults = TRUE)
```

# Create voyage-level summaries
```{r}
sql<-glue::glue("
#standardSQL
  WITH main_voyage AS(
  SELECT
    mmsi,
    gear,
    flag,
    EXTRACT(YEAR
    FROM
      departure_timestamp) AS year,
    from_anchorage_id,
    from_anchorage_name,
    from_port_name,
    departure_timestamp,
    departure_date,
    to_anchorage_id,
    to_anchorage_name,
    to_port_name,
    arrival_timestamp,
    SUM(hours) time_at_sea_hours,
    SUM(fishing_hours) fishing_hours,
    SUM(distance_km) distance_traveled_km,
    (SUM(CASE
          WHEN fishing_foreign_eez THEN 1
          ELSE 0 END) > 0) fishing_foreign_eez,
    (SUM(CASE
          WHEN fishing_high_seas THEN 1
          ELSE 0 END) > 0) fishing_high_seas,
    (SUM(CASE
          WHEN fishing_ntz THEN 1
          ELSE 0 END) > 0) fishing_ntz,
    (SUM(CASE
          WHEN suspicious_econ THEN 1
          ELSE 0 END)) / COUNT(*) fraction_suspicious_econ
  FROM
    `human_rights.poc_voyages_gridded`
  GROUP BY
    mmsi,
    gear,
    flag,
    from_anchorage_id,
    from_anchorage_name,
    from_port_name,
    departure_timestamp,
    departure_date,
    to_anchorage_id,
    to_anchorage_name,
    to_port_name,
    arrival_timestamp),
  daily_fishing AS(
  SELECT
    mmsi,
    gear,
    flag,
    from_anchorage_id,
    departure_timestamp,
    (CASE
        WHEN SUM(hours) = 0 THEN NULL
        ELSE SUM(hours) END) daily_hours,
    day
  FROM
    `human_rights.poc_voyage_ais_positions`
  GROUP BY
    mmsi,
    gear,
    flag,
    from_anchorage_id,
    departure_timestamp,
    day),
  daily_fishing_sum AS(
  SELECT
    mmsi sum_mmsi,
    gear sum_gear,
    flag sum_flag,
    from_anchorage_id sum_from_anchorage_id,
    departure_timestamp sum_departure_timestamp,
    AVG(daily_hours) mean_daily_fishing_hours
  FROM
    daily_fishing
  GROUP BY
    mmsi,
    gear,
    flag,
    from_anchorage_id,
    departure_timestamp),
  main_voyage2 AS(
  SELECT
    * EXCEPT(sum_mmsi,
      sum_gear,
      sum_flag,
      sum_from_anchorage_id,
      sum_departure_timestamp)
  FROM
    main_voyage
  LEFT JOIN
    daily_fishing_sum
  ON
    main_voyage.mmsi = daily_fishing_sum.sum_mmsi
    AND main_voyage.gear = daily_fishing_sum.sum_gear
    AND main_voyage.flag = daily_fishing_sum.sum_flag
    AND main_voyage.from_anchorage_id = daily_fishing_sum.sum_from_anchorage_id
    AND main_voyage.departure_timestamp = daily_fishing_sum.sum_departure_timestamp),
  summary_voyages AS(
  SELECT
    flag sum2_flag,
    gear sum2_gear,
    year sum2_year,
    from_port_name sum2_from_port_name,
    to_port_name sum2_to_port_name,
    AVG(time_at_sea_hours) mean_time_at_sea_hours,
    STDDEV(time_at_sea_hours) sd_time_at_sea_hours,
    AVG(fishing_hours) mean_fishing_hours,
    STDDEV(fishing_hours) sd_fishing_hours,
    AVG(distance_traveled_km) mean_distance_traveled_km,
    STDDEV(distance_traveled_km) sd_distance_traveled_km,
    AVG(mean_daily_fishing_hours) mean_mean_daily_fishing_hours,
    STDDEV(mean_daily_fishing_hours) sd_mean_daily_fishing_hours
  FROM
    main_voyage2
  GROUP BY
    sum2_flag,
    sum2_gear,
    sum2_year,
    sum2_from_port_name,
    sum2_to_port_name)
SELECT
  * EXCEPT(sum2_gear,
    sum2_flag,
    sum2_year,
    sum2_from_port_name,
    sum2_to_port_name,
    mean_time_at_sea_hours,
sd_time_at_sea_hours,
mean_fishing_hours,
sd_fishing_hours,
mean_distance_traveled_km,
sd_distance_traveled_km,
mean_mean_daily_fishing_hours,
sd_mean_daily_fishing_hours),
    (time_at_sea_hours > mean_time_at_sea_hours + {suspicious_cutff} * sd_time_at_sea_hours) suspicious_time_at_sea_hours,
    (fishing_hours > mean_fishing_hours + {suspicious_cutff} * sd_fishing_hours) suspicious_fishing_hours,
    (distance_traveled_km > mean_distance_traveled_km + {suspicious_cutff} * sd_distance_traveled_km) suspicious_distance_traveled_km,
    (mean_daily_fishing_hours > mean_mean_daily_fishing_hours + {suspicious_cutff} * sd_mean_daily_fishing_hours) suspicious_mean_daily_fishing_hours
FROM
  main_voyage2
LEFT JOIN
  summary_voyages
ON
  main_voyage2.gear = summary_voyages.sum2_gear
  AND main_voyage2.flag = summary_voyages.sum2_flag
  AND main_voyage2.year = summary_voyages.sum2_year
  AND main_voyage2.from_port_name = summary_voyages.sum2_from_port_name
  AND main_voyage2.to_port_name = summary_voyages.sum2_to_port_name")
bq_table(project = project,table = "poc_voyages",dataset = "human_rights") %>% 
  bq_table_delete()
bq_project_query(project,query = sql, destination_table = bq_table(project = project,table = "poc_voyages",dataset = "human_rights"),
                 allowLargeResults = TRUE)

```

```{r}
sql<-"
SELECT
*
FROM
`human_rights.poc_voyages`
WHERE
fishing_foreign_eez
OR fishing_high_seas
OR fishing_ntz
OR fraction_suspicious_econ > 0
OR suspicious_time_at_sea_hours
OR suspicious_fishing_hours
OR suspicious_distance_traveled_km
OR suspicious_mean_daily_fishing_hours
"
suspicious <- bq_project_query(project, sql) %>%
  bq_table_download(max_results = Inf)

suspicious_score <- suspicious %>%
  mutate(suspicious_econ = fraction_suspicious_econ >0,
         risk_score = fishing_foreign_eez+
           fishing_high_seas+
           fishing_ntz+
           suspicious_econ+
           suspicious_distance_traveled_km+
           suspicious_time_at_sea_hours+
           suspicious_fishing_hours+
           suspicious_mean_daily_fishing_hours)
```

